name: tailwindcss-extra
version: '2.0.9'
summary: Tailwind CSS standalone CLI (extra)
description: |
  Repackaged Tailwind CSS standalone CLI that comes bundled with
  daisyUI - the most popular component library for Tailwind CSS.
website: https://github.com/dobicinaitis/tailwind-cli-extra
icon: snap/local/logo.png
license: MIT

base: core24
grade: stable
confinement: strict

parts:
  tailwindcss-extra:
    plugin: dump
    source: .
    build-packages:
      - curl
    build-environment:
      - BASE_URL: https://github.com/dobicinaitis/tailwind-cli-extra/releases/download/v$SNAPCRAFT_PROJECT_VERSION
      - EXECUTABLE_PATH: $CRAFT_PART_INSTALL/tailwindcss-extra
      - to amd64:
          - DOWNLOAD_URL: $BASE_URL/tailwindcss-extra-linux-x64
      - to arm64:
          - DOWNLOAD_URL: $BASE_URL/tailwindcss-extra-linux-arm64
    override-build: |
      if [ -z "$DOWNLOAD_URL" ]; then
        echo "Target architecture [$SNAPCRAFT_ARCH_TRIPLET] is not supported. Exiting."
        exit 1
      fi

      curl -sSL $DOWNLOAD_URL -o $EXECUTABLE_PATH
      chmod +x $EXECUTABLE_PATH

      # add the tab completion script
      cp snap/local/completer.sh $CRAFT_PART_INSTALL/
    stage:
      - tailwindcss-extra
      - completer.sh

apps:
  tailwindcss-extra:
    command: tailwindcss-extra
    completer: completer.sh
    plugs:
      - home